version: "3.9"

services:
  app:
    image: node:18
    container_name: express_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    command: sh -c "./iniciar.sh"

volumes:
  mongo_data:
